### PR TITLE
feat: scrape given url and generate keywords

### PR DESCRIPTION
**Pull request by Mustafa017**
This script uses BeautifulSoup to scrape data from Google Cloud Skills Boost (GCSB) then uses the generated data to generate keywords using keyBert. Data filtering and aggregation has been done using pandas and the resulting output saved to an excel worksheet. 
You can run python notebook on Google Colab and download the generated excel file called "demo_GCSB.xlsx". If you have any suggestions on how to improve the script, you can DM me on discord (@mustee452)

### CODE REVIEW

**Comment by Mustafa017** [comment]
@neomatrix369 i have added some markdown to the notebook. Let me know how it looks.

**Comment by neomatrix369** [comment]
> @neomatrix369 i have added some markdown to the notebook. Let me know how it looks.

I saw your text but I thought every section could be explained a bit more, think of it from the perspective of a user who does not know about the notebook since you developed it, how will they understand what the end-to-end flow is and how to start and finish.

I also suggest moving the notebook under the `app` folder and create a sub-folder like `automation`, this make the work more organised.

And add a link in the README part of the page so we can click on it and get to the notebook from there - does this make sense? SO its easy to find and navigate.

**Comment by Mustafa017** [comment]
@neomatrix369 
I'll make the changes and let you know. Also, since @mbhoge has done some good work on the documentation, I'll be working with him to put the notebook under the app folder and merge his branch (https://github.com/neomatrix369/learning-path-index/tree/manishkr1754-Added-Kaggle-Dataset-Link) to main. I can continue using this branch for development.

**Comment by neomatrix369** [comment]
See if you can mention this collaborative effort in the README near the link to this notebook - let me know if you dont follow what I mean

**Pull request closed without merging**
