### PR TITLE
[Kaggle Dataset] Adding utility to fetch Dataset Metadata and saving it next to the dataset

### PR DESCRIPTION
**Pull request by neomatrix369**
The below tasks were performed via this PR:

- Adding the script to get metadata using the Kaggle API
- Renaming the .csv file, saving the downloaded dataset metadata to the right folder
- Adding docs to illustrate how to use the script

**TODO**: we still need to know how to fetch column metadata from the Dataset for eg. the descriptions added to the various columns of the .csv file in the dataset.

### CODE REVIEW

**Review by TobeTek — COMMENTED** [review]
This looks great!
Just idea, I don't know how relevant it would be to provide defaults/fillers for missing fields?

**Comment by manishkr1754** [comment]
Column field Meta-data json created manually

**Review by manishkr1754 — APPROVED** [review]
I have thoroughly reviewed the Kaggle API documentation for [Dataset MetaData](https://github.com/Kaggle/kaggle-api/wiki/Dataset-Metadata) and have rigorously tested all available commands. Regrettably, I have encountered the same issue when attempting to retrieve column field metadata. It appears that this issue has persisted for a long time, as it is also documented in a 1.5-year-old GitHub issue, [#Issue410 Kaggle API](https://github.com/Kaggle/kaggle-api/issues/410).

As it stands, it appears that there is currently no solution provided through the Kaggle API for this particular issue. In the interim, it may be prudent to consider manually generating metadata in JSON format to address this concern.

**Comment by neomatrix369** [comment]
@manishkr1754 the same thing happened here!

**Comment by neomatrix369** [comment]
@manishkr1754 we need to extend this branch/PR changes to now push the metadata for the columns data to Kaggle's Dataset, then we will be complete in our cycle.

**Comment by manishkr1754** [comment]
MetaData with column fields has been uploaded to kaggle Dataset today.

**Comment by dataoculus** [comment]
is this merged?

**Pull request merged**
